steps:
- task: GoTool@0
  displayName: 'Use Go ${{ parameters.goVersion }}'
  inputs:
    version: ${{ parameters.goVersion }}

- bash: |
    mkdir -p '$(GOPATH)/bin'
    echo '##vso[task.prependpath]$(GOROOT)/bin'
    echo '##vso[task.prependpath]$(GOPATH)/bin'
  displayName: 'Create Go Workspace'
