trigger:
  batch: true
  branches:
    include:
      - main
      - master
      - develop
      - release/*
      - feature/*
      - hotfix/*
  paths:
    exclude:
      - README.md
      - LICENSE
      - .gitignore

pr:
  autoCancel: true
  branches:
    include:
      - main
      - master
  paths:
    exclude:
      - README.md
      - LICENSE
      - .gitignore

variables:
  GOPATH: '$(Pipeline.Workspace)/gowork'

stages:
- stage: Build
  jobs:
  - job: Linux
    strategy:
      matrix:
        Go 1.15:
          go.version: '1.15'
    pool:
      vmImage: 'ubuntu-20.04'
    steps:
    - template: .github/build.yml

- stage: Tests
  jobs:
  - job: Tests
    strategy:
      matrix:
        Go 1.14:
          go.version: '1.14'
        Go 1.15:
          go.version: '1.15'
    pool:
      vmImage: 'ubuntu-20.04'
    steps:
    - template: .github/test.yml
